
### Kepolisian
GET http://localhost:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInVzZXJuYW1lIjoia2Vwb2xpc2lhbiIsInJvbGUiOiJwb2xpc2kiLCJpYXQiOjE2ODEyNjkwNzYsImV4cCI6MTY4MTI2OTA5Nn0.R8p1HHisZvvM0v1XE3SXja9dZeAx8bnqz13qtBV-T6A

###
POST http://localhost:4000/users
Content-Type: application/json

{
  "username" : "kepolisian",
  "role" : "polisi",
  "password" : "polresta",
  "confPassword" : "polresta"
}


###
POST http://localhost:4000/login
Content-Type: application/json

{
  "username" : "kepolisian",
  "password" : "polresta"
}

###
POST http://localhost:4000/users/change-password
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInVzZXJuYW1lIjoia2Vwb2xpc2lhbiIsInJvbGUiOiJwb2xpc2kiLCJpYXQiOjE2ODExMjY1MzksImV4cCI6MTY4MTIxMjkzOX0.x7fNrNmIl1hbbbpAt_cINqFhFAv6NF3UfVY-gP_-ILc
Content-Type: application/json

{
  "oldPassword" : "polresta",
  "password" : "polresta",
  "confPassword" : "polresta"
}

###
GET http://localhost:4000/token

###
DELETE http://localhost:4000/logout