
### Kepolisian
GET http://localhost:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoia2Vwb2xpc2lhbiIsInJvbGUiOiJwb2xpc2kiLCJpYXQiOjE2ODE5Mjk0NDksImV4cCI6MTY4MTkyOTQ2OX0.mIoZ5DjpeN7-GGkynQ2A3AQTHGTTyB4VuBxDXCJr8fY

###
POST http://localhost:4000/users
Content-Type: application/json

{
  "username" : "kepolisian",
  "role" : "polisi",
  "password" : "polresta",
  "confPassword" : "polresta"
}

###
POST http://localhost:4000/users
Content-Type: application/json

{
  "username" : "dishub",
  "role" : "dinas-perhubungan",
  "password" : "dinasperhubungan",
  "confPassword" : "dinasperhubungan"
}

###
POST http://localhost:4000/users
Content-Type: application/json

{
  "username" : "dinkes",
  "role" : "dinas-kesehatan",
  "password" : "dinaskesehatan",
  "confPassword" : "dinaskesehatan"
}

###
POST http://localhost:4000/users
Content-Type: application/json

{
  "username" : "rs",
  "role" : "rumah-sakit",
  "password" : "rumahsakit",
  "confPassword" : "rumahsakit"
}

###
POST http://localhost:4000/users
Content-Type: application/json

{
  "username" : "PTjasaraharja",
  "role" : "jasa-raharja",
  "password" : "jasaraharja",
  "confPassword" : "jasaraharja"
}


###
POST http://localhost:4000/login
Content-Type: application/json

{
  "username" : "kepolisian",
  "password" : "polresta"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
  "username" : "dishub",
  "password" : "dinasperhubungan"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
  "username" : "dinkes",
  "password" : "dinaskesehatan"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
  "username" : "rs",
  "password" : "rumahsakit"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
  "username" : "PTjasaraharja",
  "password" : "jasaraharja"
}


###
POST http://localhost:4000/users/change-password
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInVzZXJuYW1lIjoia2Vwb2xpc2lhbiIsInJvbGUiOiJwb2xpc2kiLCJpYXQiOjE2ODExMjY1MzksImV4cCI6MTY4MTIxMjkzOX0.x7fNrNmIl1hbbbpAt_cINqFhFAv6NF3UfVY-gP_-ILc
Content-Type: application/json

{
  "oldPassword" : "polresta",
  "password" : "polresta",
  "confPassword" : "polresta"
}

###
GET http://localhost:4000/token

###
DELETE http://localhost:4000/logout

###
POST http://localhost:4000/laporan
Content-Type: application/json

{
 "judul_kejadian": "Kecelakaan",
 "tanggal": "2021-07-01",
 "waktu": "12.00",
 "lokasi": "Jalan Raya",
 "kerugian_materil": "1000000",
 "plat_ambulance": "B 1234 ABC",
 "penyebab": "Kecelakaan",
 "keterangan": "Kecelakaan di jalan raya"
}

###
GET http://localhost:4000/laporan

###
delete http://localhost:4000/laporan/1

###
PATCH http://localhost:4000/laporan/2
Content-Type: application/json

{
 "judul_kejadian": "Sholat"
}