GET http://localhost:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInVzZXJuYW1lIjoia2Vwb2xpc2lhbiIsInJvbGUiOiJwb2xpc2kiLCJpYXQiOjE2ODEwNDc4NjgsImV4cCI6MTY4MTEzNDI2OH0.nRM9darFAQAleRO2yvadYgCFB16_h7b-0LZ9t-hLBi8
POST http://localhost:4000/users
Content-Type: application/json

{
  "username" : "kepolisian",
  "role" : "polisi",
  "password" : "polresta",
  "confPassword" : "polresta"
}

###
POST http://localhost:4000/login
Content-Type: application/json
{
  "username" : "kepolisian",
  "password" : "polresta"
}

###
POST http://localhost:4000/users/change-password
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInVzZXJuYW1lIjoia2Vwb2xpc2lhbiIsInJvbGUiOiJwb2xpc2kiLCJpYXQiOjE2ODEwNDc4NjgsImV4cCI6MTY4MTEzNDI2OH0.nRM9darFAQAleRO2yvadYgCFB16_h7b-0LZ9t-hLBi8
Content-Type: application/json

{
  "password" : "polresta",
  "confPassword" : "polrestabes"
}